FROM jenkins/jenkins:2.176.1-jdk11
# if we want to install via apt
USER root
RUN apt-get update
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install git-lfs && git lfs install
# drop back to the regular jenkins user - good practice
USER jenkins